//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }

        public static explicit operator Employee(List<dynamic> v)
        {
            throw new NotImplementedException();
        }

        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string designation { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
