version: '3.8'

services:
  api:
      build:
        context: .
        dockerfile: ApiTemplate/Dockerfile
      container_name: apitemplate_api
      depends_on:
        - db
      environment:
        - ConnectionStrings__DefaultConnection=Server=db,1433;Database=test2;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "8080:8080"
        - "8081:8081"
      networks:
        - app-network
      restart: on-failure
      
  db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sqlserver_db
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=YourStrongPassword!
      ports:
        - "1433:1433"
      networks:
        - app-network
      volumes:
        - sql-data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  sql-data: