//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_EMAIL { get; set; }
        public int EMP_ADDRESS_ID { get; set; }
        public string EMP_CODE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
    }
}
