create database EmployeeDB

CREATE TABLE EMPLOYEE
(
ID INT IDENTITY(1,1) NOT NULL,
EMP_NAME VARCHAR(20) NOT NULL,
EMP_EMAIL VARCHAR(40) NOT NULL UNIQUE,
EMP_ADDRESS_ID INT NOT NULL,
EMP_CODE VARCHAR(50) NOT NULL
)

CREATE TABLE ADDRESS
(
AD_ID INT IDENTITY(1,1) NOT NULL,
ADD_DETIALS VARCHAR(50) NULL,
ADD_STATE VARCHAR(40) NULL,
ADD_COUNTRY VARCHAR(40) NULL
)

--PRIMARY KEY
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOY PRIMARY KEY (ID)

ALTER TABLE ADDRESS
    ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (AD_ID)

--FORIGN KEY

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_TO_ADDRESS
    FOREIGN KEY (EMP_ADDRESS_ID) REFERENCES ADDRESS (AD_ID) ON DELETE CASCADE ON UPDATE CASCADE

select * from EMPLOYEE
select * from ADDRESS

create table loger
(
id int identity(1,1) not null,
Loggerfile varchar(max) null
)