//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sid { get; set; }
        public System.DateTime sdate { get; set; }
        public int cid { get; set; }
        public int iid { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual item item { get; set; }
    }
}
