//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_GENDER { get; set; }
        public Nullable<int> STD_AGE { get; set; }
        public Nullable<int> STD_CLASS { get; set; }
        public Nullable<int> T_ID { get; set; }
    }
}
